spring.application.name=test
spring.config.import=optional:file:.env[.properties]
app.pdfmerge.path=${IMAGE_DOWNLOAD_PATH}
app_frontend_url=${FRONT_END_URl}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE_TO_UPLOAD}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE_TO_UPLOAD}


